.TH ISO2CHD 1 "September 2026" "iso2chd 1.1.0" "User Commands"
.SH NAME
iso2chd \- Batch ISO to CHD conversion utility for disk images
.SH SYNOPSIS
.B iso2chd
[\fIDIRECTORY\fR]
.br
.B iso2chd
[\fIOPTION\fR]
.SH DESCRIPTION
.B iso2chd
scans a target directory for PlayStation 2 or other disc image \fI.iso\fR files, invokes \fBchdman createdvd\fR to compress them into high-efficiency \fI.chd\fR files, and deletes the original \fI.iso\fR upon a successful build.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help summary and exit.
.TP
\fB\-v\fR, \fB\-\-version\fR
Output version information and exit.
.SH EXAMPLES
.TP
.B iso2chd
Runs the utility interactively, prompting for a path.
.TP
.B iso2chd /mnt/ps2games
Executes batch conversion on the specified mount point.
.SH SEE ALSO
.BR chdman (1)
.SH AUTHOR
Abhimanyu Bhadauriya
